USE [master]
GO
/****** Object:  Database [ShopTheThao]    Script Date: 3/16/2023 4:46:50 PM ******/
CREATE DATABASE [ShopTheThao]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ShopTheThao', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ShopTheThao.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ShopTheThao_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ShopTheThao_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ShopTheThao] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ShopTheThao].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ShopTheThao] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ShopTheThao] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ShopTheThao] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ShopTheThao] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ShopTheThao] SET ARITHABORT OFF 
GO
ALTER DATABASE [ShopTheThao] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ShopTheThao] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ShopTheThao] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ShopTheThao] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ShopTheThao] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ShopTheThao] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ShopTheThao] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ShopTheThao] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ShopTheThao] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ShopTheThao] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ShopTheThao] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ShopTheThao] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ShopTheThao] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ShopTheThao] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ShopTheThao] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ShopTheThao] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ShopTheThao] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ShopTheThao] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ShopTheThao] SET  MULTI_USER 
GO
ALTER DATABASE [ShopTheThao] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ShopTheThao] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ShopTheThao] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ShopTheThao] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ShopTheThao] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ShopTheThao] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ShopTheThao] SET QUERY_STORE = OFF
GO
USE [ShopTheThao]
GO
/****** Object:  Table [dbo].[ChiTietDonHang]    Script Date: 3/16/2023 4:46:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChiTietDonHang](
	[madon] [int] NOT NULL,
	[masanpham] [int] NOT NULL,
	[soluong] [int] NULL,
	[gia] [decimal](18, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[madon] ASC,
	[masanpham] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DanhMuc]    Script Date: 3/16/2023 4:46:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DanhMuc](
	[madanhmuc] [int] IDENTITY(1,1) NOT NULL,
	[tendanhmuc] [nvarchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[madanhmuc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DonHang]    Script Date: 3/16/2023 4:46:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DonHang](
	[madon] [int] IDENTITY(1,1) NOT NULL,
	[thanhtoan] [bit] NULL,
	[giaohang] [bit] NULL,
	[ngaydat] [date] NULL,
	[ngaygiao] [date] NULL,
	[makh] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[madon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KhachHang]    Script Date: 3/16/2023 4:46:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KhachHang](
	[makh] [int] IDENTITY(1,1) NOT NULL,
	[hoten] [nvarchar](50) NULL,
	[tendangnhap] [varchar](20) NULL,
	[matkhau] [varchar](10) NULL,
	[email] [varchar](50) NULL,
	[diachi] [nvarchar](100) NULL,
	[dienthoai] [varchar](15) NULL,
	[ngaysinh] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[makh] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SanPham]    Script Date: 3/16/2023 4:46:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SanPham](
	[masanpham] [int] IDENTITY(1,1) NOT NULL,
	[madanhmuc] [int] NULL,
	[tensanpham] [nvarchar](100) NOT NULL,
	[hinh1] [varchar](50) NULL,
	[hinh2] [varchar](50) NULL,
	[hinh3] [varchar](50) NULL,
	[hinh4] [varchar](50) NULL,
	[mota] [nvarchar](max) NULL,
	[giaban] [decimal](18, 0) NULL,
	[ngaycapnhat] [smalldatetime] NULL,
	[soluongton] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[masanpham] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SanPham] ADD  CONSTRAINT [DF_SanPham_soluongton]  DEFAULT ((0)) FOR [soluongton]
GO
ALTER TABLE [dbo].[ChiTietDonHang]  WITH CHECK ADD FOREIGN KEY([madon])
REFERENCES [dbo].[DonHang] ([madon])
GO
ALTER TABLE [dbo].[ChiTietDonHang]  WITH CHECK ADD FOREIGN KEY([masanpham])
REFERENCES [dbo].[SanPham] ([masanpham])
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD FOREIGN KEY([makh])
REFERENCES [dbo].[KhachHang] ([makh])
GO
ALTER TABLE [dbo].[SanPham]  WITH CHECK ADD FOREIGN KEY([madanhmuc])
REFERENCES [dbo].[DanhMuc] ([madanhmuc])
GO
USE [master]
GO
ALTER DATABASE [ShopTheThao] SET  READ_WRITE 
GO
